languageCode = "en-us"
title = "Fast Hugo"
googleAnalytics = "xx-xxx-x"
baseurl = "/"
canonifyURLs = false
rssLink = ""

[params]
  description = "Optimized Hugo Website Boilerplate."
  email = "hello@fasthugo.com"
  dateForm = "Monday, Jan 2, 2006"

[permalinks]
  post = ":year/:title/"

[[menu.main]]
    name = "contact"
    url = "/contact/"
